%%{init: {'flowchart': {'curve': 'basis'}} }%%
stateDiagram-v2
    direction LR

    [*] --> Disconnected

    Disconnected --> Connected: session_notify\nPOST /api/sessions/auto-heartbeat

    Connected --> Disconnected: session_end_event\nPOST /api/sessions/end
    Connected --> Disconnected: 管理者操作\nPUT /api/sessions/{id} status=disconnected
